### ISSUE TITLE
Comment on app store

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/eu.benext#19]
https://apps.athom.com/app/eu.benext#comment-59770b3ca805e0fc0d41ddc1

I have it running so far, but are there more people that have issues with the Tag Reader 500? For pairing it with homey the reader must be very close to homey (5 centimeters), or else it won't pair. I now also have the problem that the battery is dead already after 1,5 weeks. According the specs it would last for 2 or 5 years.

**Comment by FreeFrags** [comment]
Pairing was a pain for me too even if i kept it close by it took 5 tries. When it fails it does so in the middle of syncing the security commands if i remember correctly. Then you have to remove the device from the z wave network in the settings and retry.

As for the battery i havent used the device long enough yet but 1.5 week? Thanks for the heads up i will need to add an extra way to disarm the system then wouldnt want your alarm flow triggering without a way to turn it off.

**Comment by FreeFrags** [comment]
Any news on the battery life? Will install my tag reader soon :)

**Comment by MartinMotz** [comment]
I also have the above mentioned batteryproblem. Thought it was a failure for my device only.
it seems that more people have this experience. 
The Device works excellent, except the short batterylife. Any news?
