### ISSUE TITLE
BE next laad error homey next gen

### ISSUE THREAD

**Issue by Cracker1034** [Inversion-NL/eu.benext#28]
Bij downloaden app error. Detail: invalid driver class security [object Object]

**Comment by bergh-io** [comment]
I have the same problem. Homey version 2.0.0, app version 2.0.0.244.

**Comment by rowins** [comment]
Benext app isn't homey v2.0 compatible :(

**Comment by Superbuis** [comment]
Same here :(

**Comment by Superbuis** [comment]
Since the Homey v2.0.2 the error message changed to "This app is incompatible with Homey. Try again".

**Comment by athomey** [comment]
Same here. No news? Got a few Benext dimmers which stopped working.

**Comment by Inversion-NL** [comment]
Duplicate of #27
