### ISSUE TITLE
Benext P1 dongle v1.0.4

### ISSUE THREAD

**Issue by Hbaalen** [Inversion-NL/eu.benext#37]
I installed Beta version 1.04 of the Benext app on my Homey Pro.
When I try to pair my P1 dongle nothing happens, and in the end I get the message "no Z-wave device found".
The P1 dongle used to work fine on my old Homey.

Best regards,
Hans

**Comment by mapulu** [comment]
"no Z-wave device found" looks not like an app issue. Homey can't find the device.
Make sure the P1 dongle is in inclusion mode, maybe you have to exclude/reset the P1 dongle first.
Also try to bring homey near as possible to the device for pairing.

**Comment by Hbaalen** [comment]
Thanx for your reply.
I did try exactly the things you discribed.
When I try to pair I bring Homey to the P1 dongle with a powerbank.
When I push the button on the P1 for 3 seconds the led starts blinking irregular for some seconds. So it seems there is some communication.
After that nothing untill the homey pairing proces times out (I think), then the message appears.

**Comment by mapulu** [comment]
Sorry I can't help you at the moment, it is not an app issue. It is an pairing issue.

**Comment by Hbaalen** [comment]
ok. thank you for your time.
