### ISSUE TITLE
Tagreader 500 - Can't add tags or pin (app v1.0.4)

### ISSUE THREAD

**Issue by Markos84** [Inversion-NL/eu.benext#41]
I can't manage to register a tag or pin with the tagreader 500.

This is what I tried:
Toggle "Tag Approval" in the advanced settings section
Home> Number> Enter (for pin)
or
Home> button on the keypad and hold the tag in front. (for rfid tag)

But he doesn't seem to register anything even if I perform these actions right next to homey.

Just to be sure, I removed all the tags once more, because I also used them with the old version.

**Comment by mapulu** [comment]
I copied the driver from zipato app which is a further development of the BeNext Tagreader driver. The zipato and Benext tag reader are the same devices from different brands.

I will look into it when I got time. Also enabled debug for this for future version.

**Comment by Markos84** [comment]
thanks for your time and effort to breathe new life into this app

**Comment by mapulu** [comment]
It seems the driver is written for local mode but the device is in gateway mode.

Please go to the device -> advanced settings -> raw configuration parameter -> 7,1,1;
Wake up the device when saving the settings (Press 4 seconds the enter button)
