### ISSUE TITLE
Crash at device.js:116

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/eu.benext#42]
A crash occurred for your app (version 1.0.5) at Aug 23, 2019 6:56 AM (UTC).

Homey software version: 2.5.2

at /drivers/heating_control/device.js:116
				if (node && node && node.CommandClass && node.CommandClass.
				^

I'v added below screenshot of the message because Github messes up al the tabs/spacing:
![image](https://user-images.githubusercontent.com/15921016/63575268-ef731980-c589-11e9-9da0-174349e9201a.png)

**Comment by Inversion-NL** [comment]
I've receive 5 more of the exact same crashes.
However I'm not able to see in the crash if its the same Homey/user.

**Comment by Willy0611** [comment]
App crashed today directly after upgrading to 1.0.5.

**Comment by mapulu** [comment]
I need "this" ...
Could you update to v1.0.6 ?

**Comment by Inversion-NL** [comment]
Done, lets hope Athom quickly approves!

**Comment by Inversion-NL** [comment]
Still not approved...

**Comment by Inversion-NL** [comment]
Just published 1.0.6
