### ISSUE TITLE
/drivers/heating_control/device.js:144 callback is not defined

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/eu.benext#44]
/drivers/heating_control/device.js:144
return callback(null, true);
ReferenceError: callback is not defined

![Screenshot_20190824-161441](https://user-images.githubusercontent.com/15921016/63638576-6d1e4e80-c68a-11e9-9fed-7550f31c730d.png)

**Comment by mapulu** [comment]
In the old driver it was called in a function so there was a callback. I removed that callback.
Hopefully the last error. I will also look over the code again on Monday
