### ISSUE TITLE
app keeps crashing since v1.0.6

### ISSUE THREAD

**Issue by B3rt** [Inversion-NL/eu.benext#47]
Since the last update and last homey update this apps keep crashing.

A restart of the app does not have any effect.

I send a report to developer, here is the detailed code of the report:
bb5f11bc-070e-418a-8c2b-957d4ca282da

Hope this can be fixed, my heating (luckily i do not need it at the moment) is not working anymore.

**Comment by mapulu** [comment]
Should be solved in v1.0.7

**Comment by B3rt** [comment]
when will v1.0.7 be available?

**Comment by mapulu** [comment]
Now... Does it crash again?

**Comment by Inversion-NL** [comment]
v1.0.7 had been released a few hours ago

**Comment by B3rt** [comment]
It works fine again after the update, thx
