### ISSUE TITLE
Please Add Door / Windows sensor

### ISSUE THREAD

**Issue by sjaakie33** [Inversion-NL/eu.benext#7]
Good day,

Please Add Door / Windows sensor

With kind regards,

René Ardley

**Comment by RoadXY** [comment]
I don't have the sensor as well as the time to implement it. However your more than welcome to create an Pull Request to add the driver.

**Comment by Inversion-NL** [comment]
I don't have the sensor as well as the time to implement it. However your more than welcome to create an Pull Request to add the driver.
